<?php
$this->headTitle('Luncheon - manage your lunch!');

?>
<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <?php echo $this->layout()->content; ?>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
